language: php

php:
  - 8.0
  - 8.1
  - 8.2

env:
  - COMPOSER_DEPENDENCIES=""
  - COMPOSER_DEPENDENCIES="--prefer-lowest"

jobs:
  include:
    - php: nightly
      env: COMPOSER_DEPENDENCIES="--ignore-platform-reqs"

install:
  - travis_retry composer update --no-interaction $COMPOSER_DEPENDENCIES

script:
  - composer run build
